import React from 'react';
import { X, Bot, User, Clock } from 'lucide-react';

const TranscriptModal = ({ isOpen, onClose, transcript, caller, date }) => {
  if (!isOpen) return null;

  // Simple parser for common transcript formats (e.g., "AI: Hello", "User: Hi")
  const parseTranscript = (raw) => {
    if (!raw) return [];
    
    // Check if it's JSON (sometimes stored as a list of dicts)
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
    } catch (e) {}

    // Otherwise, parse as line-by-line text
    return raw.split('\n').filter(line => line.trim()).map((line, idx) => {
      if (line.startsWith('AI:') || line.startsWith('Bot:')) {
        return { role: 'assistant', content: line.replace(/^(AI|Bot):/, '').trim(), id: idx };
      }
      if (line.startsWith('User:') || line.startsWith('Patient:')) {
        return { role: 'user', content: line.replace(/^(User|Patient):/, '').trim(), id: idx };
      }
      // Fallback for lines without clear prefixes
      return { role: 'unknown', content: line.trim(), id: idx };
    });
  };

  const messages = parseTranscript(transcript);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl w-full max-w-2xl max-h-[85vh] flex flex-col shadow-2xl border border-gray-100 animate-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="p-6 border-b border-gray-100 flex items-center justify-between shrink-0">
          <div>
            <h3 className="text-xl font-bold text-gray-900 tracking-tight">Call Transcript</h3>
            <div className="flex items-center gap-3 mt-1.5">
               <span className="flex items-center gap-1 text-[11px] font-bold text-gray-400 uppercase tracking-widest bg-gray-50 px-2 py-0.5 rounded-md">
                 <User size={12} className="text-gray-300" /> {caller}
               </span>
               <span className="flex items-center gap-1 text-[11px] font-bold text-gray-400 uppercase tracking-widest bg-gray-50 px-2 py-0.5 rounded-md">
                 <Clock size={12} className="text-gray-300" /> {date}
               </span>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-xl text-gray-400 hover:text-gray-900 transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        {/* Conversation Area */}
        <div className="flex-1 overflow-y-auto p-8 space-y-6 custom-scrollbar bg-gray-50/30">
          {messages.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center space-y-3 py-20">
               <div className="p-4 bg-gray-100 rounded-full text-gray-300">
                  <Bot size={40} />
               </div>
               <p className="text-sm font-bold text-gray-400 uppercase tracking-widest">No transcript available for this call</p>
            </div>
          ) : (
            messages.map((msg) => (
              <div 
                key={msg.id} 
                className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                <div className={`flex gap-4 max-w-[85%] ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 shadow-sm ${
                    msg.role === 'user' ? 'bg-white border border-gray-100 text-gray-400' : 'bg-gray-900 text-white'
                  }`}>
                    {msg.role === 'user' ? <User size={16} /> : <Bot size={16} />}
                  </div>
                  <div className={`p-4 rounded-2xl text-sm font-medium leading-relaxed shadow-sm ${
                    msg.role === 'user' 
                      ? 'bg-gray-900 text-white rounded-tr-none' 
                      : 'bg-white border border-gray-100 text-gray-800 rounded-tl-none'
                  }`}>
                    {msg.content}
                  </div>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-100 shrink-0 bg-gray-50/50 flex justify-between items-center">
           <div className="text-[10px] font-bold text-gray-400 uppercase tracking-[2px]">
             Auto-generated by Gray Solutions AI
           </div>
           <button 
             onClick={onClose}
             className="px-6 py-2 bg-gray-900 text-white text-xs font-bold rounded-xl hover:scale-105 active:scale-95 transition-all shadow-lg shadow-gray-200"
           >
             Close Viewer
           </button>
        </div>
      </div>
    </div>
  );
};

export default TranscriptModal;
